---
- name: Update apt-cache and upgrade
  hosts: oracleServer
  tasks:
    - name: Upgrade packages
      become: true
      ansible.builtin.package:
        update_cache: true
        upgrade: true
