---
- name: update apt-cache and upgrade
  # 'all' is okay here, because the fail task will force the user to specify a limit on the command line, using -l or --limit
  hosts: all 
  tasks:
    - name: checking limit arg
      fail:
        msg: "you must use -l or --limit - when you really want to use all hosts, use -l 'all'"
      when: ansible_limit is not defined
      run_once: true

    - name: apt
      become: true
      apt:
          update_cache: yes
          upgrade: 'yes'

